general {
    grace = 3
    hide_cursor = true
    disable_loading_bar = true
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/black mouunts.jpg
    color = rgba(0, 0, 0, 0.8)
    
    # Эффекты размытия
    blur_passes = 3
    blur_size = 5
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.3000
}

# Time
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%H:%M')"
    color = rgba(255, 255, 255, 1)
    font_size = 96
    font_family = Inter Bold
    
    position = 0, 300
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    color = rgba(255, 255, 255, 0.8)
    font_size = 24
    font_family = Inter Medium
    
    position = 0, 375
    halign = center
    valign = center
}

# Temperature
label {
    monitor =
    text = cmd[update:300000] curl -s "wttr.in?format=%t+%C"
    color = rgba(173, 216, 230, 1)
    font_size = 28
    font_family = Inter Medium
    
    position = 0, 200
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = rgba(100, 149, 237, 1)
    fail_color = rgba(220, 20, 60, 1)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    
    position = 0, -350
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = rgba(255, 255, 255, 0.7)
    font_size = 18
    font_family = Inter
    
    position = 0, -300
    halign = center
    valign = center
}
