general {
    lock_cmd = pidof hyprlock || hyprlock       # lock command
    unlock_cmd = killall hyprlock               # unlock command
    before_sleep_cmd = loginctl lock-session    # hyprlock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # screen on after suspend
}

# hyprlock & screnn
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off && hyprlock
    on-resume = hyprctl dispatch dpms on
}

# suspend
listener {
    timeout = 900 
    on-timeout = systemctl suspend
}
