[main]
font=JetBrains Mono Nerd Font:size=15:style=Bold

[cursor]
style=beam
blink=yes

[colors]
alpha=0.3
foreground=FFFFFF
background=000000
# regular colors
regular0=000000
regular1=ff0000
regular2=00ff00
regular3=ffff00
regular4=0000ff
regular5=ff00ff
regular6=00ffff
regular7=ffffff

# bright colors
bright0=000000
bright1=ff0000
bright2=00ff00
bright3=ffff00
bright4=0000ff
bright5=ff00ff
bright6=00ffff
bright7=ffffff
