[main]
font=JetBrains Mono Nerd Font:size=15:style=Bold
initial-window-size-pixels=960x540

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000
multiplier=3.0

[colors]
alpha=1
foreground=F1F8F1
background=101020
# regular colors
regular0=0D1117
regular1=C32424
regular2=24C391
regular3=C3A924
regular4=2455C3
regular5=C224C3
regular6=24BAC3
regular7=E8ECF2

# bright colors
bright0=3B4D68
bright1=D93030
bright2=30D9A4
bright3=D9BD30
bright4=3063D9
bright5=D930D9
bright6=30D1D9
bright7=FFFFFF
